platform:ios,'7.0'#(注明开发平台及版本)

target 'ReactOC' do
pod 'React'
pod 'React/RCTText'
pod 'React/RCTNetwork'
pod 'React/RCTWebSocket'
pod 'React/RCTImage'
pod 'AFNetworking','~>2.5.3'#(~2.5.3为版本号，忽略不写即为最新版本)
pod 'SDWebImage','~>3.7.2'
pod  'RBStoryboardLink','~>0.1'
pod 'MTLFMDBAdapter','0.2.0'
pod  'MBProgressHUD','0.9.2'
pod 'TPKeyboardAvoiding','1.2.11'
pod 'MarqueeLabel','2.5.0'
pod 'SWTableViewCell','0.3.7'
pod 'Reachability','3.2'
pod 'WYPopoverController','0.3.9'
pod 'KTScannerView','1.0'
pod 'UMengAnalytics-NO-IDFA','3.6.7'
pod 'SVPullToRefresh','0.4.1'
pod 'OBShapedButton','1.0.2'
pod 'PNChart','~>0.7'
pod 'Bugly','1.4.8'
pod 'iToast','0.0.1'
pod 'SBJson','3.1.1'
pod 'SSKeychain’,‘1.4.0'
pod 'BaiduMapKit','~>3.0.0'
pod 'RongCloudIMKit','~>2.4.0'

end
